In [1]:
import numpy as np

# shape, dtype

In [14]:
test_array = np.array([[1,4,5,8],[2,4,1,4]], float)
print(test_array,"\n")
print(test_array.dtype)
print(test_array.shape)
print(test_array.size)
print(test_array.nbytes)

[[1. 4. 5. 8.]
 [2. 4. 1. 4.]] 

float64
(2, 4)
8
64


# reshape

In [24]:
test_matrix = np.array([[1,2,3,4],[1,2,5,8]])
print(test_matrix.shape)
print(test_matrix.reshape(8,).shape,"\n")

print(test_matrix.reshape(4,2),"\n")
print(test_matrix.reshape(2,2,2),"\n")

print(test_matrix.reshape(1,-1,2))

(2, 4)
(8,) 

[[1 2]
 [3 4]
 [1 2]
 [5 8]] 

[[[1 2]
  [3 4]]

 [[1 2]
  [5 8]]] 

[[[1 2]
  [3 4]
  [1 2]
  [5 8]]]


# flatten

In [28]:
test_matrix = np.array([[[1,2,3,4],[1,2,5,8]],[[1,2,3,4],[1,2,5,8]]])
test_matrix

array([[[1, 2, 3, 4],
        [1, 2, 5, 8]],

       [[1, 2, 3, 4],
        [1, 2, 5, 8]]])

In [30]:
test_matrix.flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])

# indexing slicing

In [33]:
a = np.array([[1,2,3],[4.5,5,6]],int)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
a[0,0] == a[0][0]
a[0,0] = 10
a

array([[10,  2,  3],
       [ 4,  5,  6]])

In [41]:
a = np.array([[1,2,3,4,5,],[6,7,8,9,10]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [40]:
a[:,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [47]:
a[0:1,2:4]

array([[3, 4]])

In [51]:
a[::2,::2]

array([[1, 3, 5]])

# creation function

In [52]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [53]:
np.arange(0,5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [56]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [59]:
np.zeros(shape = (10,), dtype = np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [66]:
np.empty(shape = (10,), dtype = np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 9, 0], dtype=int8)

In [69]:
np.identity(n=5, dtype = np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

In [71]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [73]:
np.eye(3,5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [78]:
matrix = np.arange(0,9).reshape(3,3)
np.diag(matrix)

array([0, 4, 8])

In [103]:
A = np.random.normal(0,1,100).reshape(5,20)
A

array([[-1.43028401, -1.88149573, -1.04562057,  0.21730475,  0.00474415,
         1.39069761,  1.22544964,  0.79825878, -0.04090174,  0.35860128,
        -0.08167372,  1.199762  ,  1.24751466, -0.37515606, -1.43883011,
         0.2631261 ,  0.71356644, -1.24041288,  0.47206568,  1.04865884],
       [-0.68371653,  1.28077619,  0.63112528,  1.34357641,  2.29790481,
         0.02958185, -0.04085122, -0.30884699,  0.1729751 ,  0.28109108,
        -1.14501984,  1.83686685, -0.68247064, -1.0874052 ,  0.74612689,
        -0.04375569, -0.87947077,  0.50071293,  0.1371596 ,  0.38623905],
       [ 1.53419426, -1.28513591,  0.38295652,  0.48878369, -1.92343114,
        -0.32290826,  0.22372466,  0.7437895 ,  0.21176512, -0.83130567,
         0.89605684, -0.78463694, -2.69879434,  1.08192293, -0.14563415,
         0.7914801 ,  0.08057673, -0.58881567,  0.20419581,  0.64484622],
       [-0.1494955 , -0.6353217 ,  1.31188115, -0.28994732,  0.59243377,
         1.50079401, -0.63867927, -0.35964293, -

In [104]:
A.sum()

3.551718330615147

In [105]:
print(A.mean(axis=0))
print(A.mean(axis=1))
A.mean()

[-0.16524042 -0.22520203 -0.16614682  0.27203111  0.09355773  0.35540115
 -0.19533263  0.52827458 -0.15626637 -0.02880373  0.14470527  0.82198493
 -0.47323518 -0.66204017 -0.41612337  0.86392686 -0.11281318  0.1342807
 -0.06893168  0.16631692]
[ 0.07026875  0.23862996 -0.06481849  0.0383387  -0.10483302]


0.03551718330615147

In [106]:
A.std()

1.0427869506967478

# concatenate

In [109]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [110]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [112]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])
print("b : ", b)
b = b[np.newaxis,:]
print("b : ", b)
np.concatenate((a,b.T), axis = 1)

b :  [5 6]
b :  [[5 6]]


array([[1, 2, 5],
       [3, 4, 6]])

In [115]:
test_a = np.array([[1,2,3],[4,5,6],[7,8,9]], float)
test_a + test_a

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 16., 18.]])

In [116]:
test_a * test_a

array([[ 1.,  4.,  9.],
       [16., 25., 36.],
       [49., 64., 81.]])

In [118]:
test_a * test_a[0,:]

array([[ 1.,  4.,  9.],
       [ 4., 10., 18.],
       [ 7., 16., 27.]])

In [131]:
test_b = np.arange(9).reshape(3,3)
test_a.dot(test_b)

array([[ 24.,  30.,  36.],
       [ 51.,  66.,  81.],
       [ 78., 102., 126.]])

In [132]:
test_a.T

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

In [133]:
test_a + 3

array([[ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [134]:
test_a + np.arange(3).reshape(3,)

array([[ 1.,  3.,  5.],
       [ 4.,  6.,  8.],
       [ 7.,  9., 11.]])

# comparisons

In [136]:
a = np.arange(10)

In [137]:
a < 4

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [138]:
np.all(a<10)

True

In [139]:
np.any(a<5)

True

In [140]:
test_a = np.array([1,3,5], float)
test_b = np.array([5,3,1], float)
test_a > test_b

array([False, False,  True])

In [141]:
test_a == test_b

array([False,  True, False])

In [142]:
np.where(a > 0, 3, 2)

#np.isnan
#np.isfinite

array([2, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [144]:
# index 반환
np.argmax(a)

9

In [145]:
# index 반환
np.argmin(a)

0

In [148]:
# index 반환
a.argsort()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# boolean index, fancy index

In [150]:
test_array[test_array > 3]

array([4., 5., 8., 4., 4.])

In [157]:
a = np.array([1,2,3,4,5],float)
b = np.array([1,1,2,2,3,3,4,3], int)
a.take(b)

array([2., 2., 3., 3., 4., 4., 5., 4.])